package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            githubIssues {
                id = "PROJECT_EXT_4"
                displayName = "virusbear/Metrix"
                repositoryURL = "https://github.com/virusbear/Metrix"
                authType = accessToken {
                    accessToken = "credentialsJSON:a02fadd7-cf69-4459-9f39-95803a20a310"
                }
            }
        }
    }
}
